id: P82A23237
initial_creation_type: input
source_metadata:
  title: Nyoshul Lungtok Series
  language: pt
  description: 'Texts by the great Dzogchen master Nyoshul Lungtok Tenpe Nyima (smyo
    shul lung rtogs bstan pa''i nyi ma, 1829–1901/2):'
  volume:
    4b45f75a24464d0891c47ce18b3237b7:
      title: Bodhicitta Aspiration
      parent: Prayers and Practices
    53c0960793344d9f8d85b62fc7eb7fc6:
      title: Prayer to Avalokiteśvara
      parent: Prayers and Practices
created_at: '2022-03-01T01:06:42.461704'
last_modified_at: '2022-03-01T01:06:42.461706'
